[package]
name = "lexer"
version = "0.1.0"
edition = "2024"

[lib]
path = "./src/lib.rs"

[dependencies]
db = { workspace = true }
regex = { workspace = true }
mysql = { workspace = true }
unicode-segmentation = { workspace = true }