[package]
name = "db"
version = "0.1.0"
edition = "2024"

[lib]
path = "./src/lib.rs"

[dependencies]

mysql = { workspace = true }
types ={ workspace = true }
diesel = { workspace = true }
shared = { workspace = true }
tracing = { workspace = true }