name: ci

on: [pull_request]

jobs:
  clippy:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: cargo clippy on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libdbus-1-dev

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo clippy --locked

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: cargo test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libdbus-1-dev

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo test --all-targets --workspace

  fmt:
    name: cargo rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - uses: actions-rust-lang/rustfmt@v1
